parameters:
    version: '1.1.5'
    locale: 'en-GB'
    uuid_regex: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $defaultLocale: '%locale%'
            $publicPath: '%kernel.project_dir%/public'
            $assetsPath: '%kernel.project_dir%/assets'
            $paginationItemsPerPage: "%env(APP_PAGINATION_ITEMS_PER_PAGE)%"

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Models,Repository,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    #Kernel listeners
    App\EventListener\TranslationCommandListener:
        tags:
            - { name: kernel.event_listener, event: console.terminate }

    App\EventListener\ContextListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 255 }
    App\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 15 }
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: doctrine.event_listener, event: postUpdate, lazy: true }
    App\EventListener\FilterListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
    App\EventListener\ActivityListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\EventListener\NonceListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }
    App\EventListener\SeenListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response}
    App\EventListener\LogQueueListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 5 }

    App\EventListener\AccessDeniedListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, lazy: true }

    #Global listeners
    App\EventListener\ItemsCounterListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }

    App\EventListener\ChildrenCounterListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }

    App\EventListener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate, lazy: true }
    App\EventListener\OwnershipListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
    App\EventListener\ColorListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
    App\EventListener\UploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
            - { name: doctrine.event_listener, event: postRemove, lazy: true }
            - { name: doctrine.event_listener, event: postLoad, lazy: true }
    App\EventListener\LoggableListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist, lazy: true, priority: -5 }
            - { name: doctrine.event_listener, event: preRemove, lazy: true, priority: -5 }
            - { name: doctrine.event_listener, event: onFlush, lazy: true, priority: -5 }

    #Entity listeners
    App\EventListener\Entity\AlbumListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    App\EventListener\Entity\PhotoListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    App\EventListener\Entity\CollectionListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    App\EventListener\Entity\ItemListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    App\EventListener\Entity\WishlistListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    App\EventListener\Entity\WishListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
    App\EventListener\Entity\UserListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }
            - { name: doctrine.event_listener, event: preUpdate, lazy: true }
            - { name: doctrine.event_listener, event: preRemove, lazy: true }

    #Log
    App\Service\Log\Logger\CollectionLogger:
        tags: [app.logger]
    App\Service\Log\Logger\ItemLogger:
        tags: [app.logger]
    App\Service\Log\Logger\TagLogger:
        tags: [app.logger]
    App\Service\Log\Logger\DatumItemLogger:
        tags: [app.logger]
    App\Service\Log\Logger\DatumCollectionLogger:
        tags: [app.logger]
    App\Service\Log\Logger\AlbumLogger:
        tags: [app.logger]
    App\Service\Log\Logger\WishlistLogger:
        tags: [app.logger]
    App\Service\Log\LoggerChain:
        arguments: [!tagged app.logger]